package com.oxymium.si2gassistant.ui.routes

enum class AppScreens {
    SPLASH_SCREEN,
    GREETINGS_SCREEN,
    METRICS_SCREEN,
    PERSONS_SCREEN,
    BUG_TICKETS_SCREEN,
    REPORT_BUG_SCREEN,
    SUBMIT_SUGGESTION_SCREEN,
    SUBMIT_PERSON_SCREEN,
    SUGGESTIONS_SCREEN
}