package com.oxymium.si2gassistant.ui.routes

enum class AppScreen {
    SPLASH_SCREEN, // FIRST SCREEN
    GREETINGS_SCREEN, // COMMON SCREEN
    METRICS_SCREEN,
    PERSONS_SCREEN,
    BUG_TICKETS_SCREEN,
    REPORT_BUG_SCREEN,
    SUBMIT_SUGGESTION_SCREEN,
    SUBMIT_PERSON_SCREEN,
    SUGGESTIONS_SCREEN,
    CHAT_SCREEN
}